## Broadcasting

In [1]:
import numpy as np
A = np.array([[56.0,0.0,4.4,68.8],
             [1.2,104.0,52.0,8.0],
             [1.8,135.0,99.0,0.9]])
A

array([[ 56. ,   0. ,   4.4,  68.8],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [3]:
cal = A.sum(axis=0) #dikey sütun toplamı
cal

array([ 59. , 239. , 155.4,  77.7])

In [4]:
percentage = 100*A/cal.reshape(1,4)
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.54568855],
       [ 2.03389831, 43.51464435, 33.46203346, 10.2960103 ],
       [ 3.05084746, 56.48535565, 63.70656371,  1.15830116]])

## Python - Numpy Vectors

In [5]:
a = np.random.randn(5)
a

array([ 1.1666206 ,  0.90418806,  1.05944292, -0.86684234,  0.24349709])

In [6]:
a.shape #a birinci dereceden dizidir ve ne satır ne de sütun vektörüdür (rank one array)

(5,)

In [7]:
a.T

array([ 1.1666206 ,  0.90418806,  1.05944292, -0.86684234,  0.24349709])

In [8]:
np.dot(a,a.T)

4.111685433725524

**NOT:** Neural network için yapısı (n,) veya birinci dereceden dizi veri yapıları kullanılması önerilmez. Çünkü satır veya sütun vektörü olmadığı için gösterilen davranışlar ve ortaya çıkacak hatalar kestirilemeyebilinir.

In [9]:
a = np.random.randn(5,1)
a

array([[-0.03759346],
       [-1.69968824],
       [-0.63398131],
       [ 0.45364749],
       [ 0.11715634]])

In [10]:
a.T

array([[-0.03759346, -1.69968824, -0.63398131,  0.45364749,  0.11715634]])

**NOT:** (5,1) boyutundaki matris ile birinci dereceden dizi arasındaki fark birinin (matris) çift, digerinin (bdd) tek parantez ile gösterilmesidir.

In [12]:
np.dot(a,a.T)

array([[ 1.41326840e-03,  6.38971654e-02,  2.38335523e-02,
        -1.70541798e-02, -4.40431250e-03],
       [ 6.38971654e-02,  2.88894010e+00,  1.07757057e+00,
        -7.71059304e-01, -1.99129256e-01],
       [ 2.38335523e-02,  1.07757057e+00,  4.01932297e-01,
        -2.87604029e-01, -7.42749306e-02],
       [-1.70541798e-02, -7.71059304e-01, -2.87604029e-01,
         2.05796046e-01,  5.31476805e-02],
       [-4.40431250e-03, -1.99129256e-01, -7.42749306e-02,
         5.31476805e-02,  1.37256084e-02]])

In [13]:
assert(a.shape == (5,1)) # vektör boyutundan emin olmak için kullanılabilir, kodun daha anlaşılır olmasına yardımcı olur

In [14]:
#herhangi bir sebepten birinci derece dizi elde edilirse reshape fonksiyonu ile tekrar boyutlandırılabilir.

In [16]:
a = a.reshape(5,1)
a

array([[-0.03759346],
       [-1.69968824],
       [-0.63398131],
       [ 0.45364749],
       [ 0.11715634]])