In [1]:
import numpy as np

In [2]:
data_list=[1,2,3,4]

In [3]:
arr=np.array(data_list)

In [4]:
arr

array([1, 2, 3, 4])

In [6]:
data_list2=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
arr2= np.array(data_list2)

In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr3=np.array([1,2,3,4])

In [10]:
arr3

array([1, 2, 3, 4])

In [11]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [16]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [19]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [20]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [21]:
np.random.randint(0,10)

5

In [24]:
np.random.randint(15)

3

In [25]:
np.random.randint(1,10,5)

array([1, 7, 8, 7, 1])

In [26]:
np.random.rand(5)

array([0.61872446, 0.54915957, 0.01195989, 0.76227622, 0.53237571])

In [27]:
np.random.randn(5)

array([-1.5493209 ,  0.72507907, -0.62689328, -0.9027374 ,  1.41325488])

In [29]:
arr= np.arange(25)

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
newArray = np.random.randint(1,100,10)

In [32]:
newArray

array([66, 96,  4, 90, 25, 76, 62, 94, 59, 64])

In [33]:
newArray.max()

96

In [34]:
newArray.min()

4

In [35]:
newArray.sum()

636

In [36]:
newArray.mean()

63.6

In [37]:
newArray.argmax()

1

In [38]:
newArray.argmin()

2

In [39]:
detArray=np.random.randint(1,100,25)

In [40]:
detArray

array([59, 59, 33, 11, 18, 44, 65, 53, 11, 48, 61, 35, 54, 56, 47, 99, 77,
       28, 25, 61, 37, 58, 56, 15, 34])

In [41]:
detArray=detArray.reshape(5,5)

In [42]:
detArray

array([[59, 59, 33, 11, 18],
       [44, 65, 53, 11, 48],
       [61, 35, 54, 56, 47],
       [99, 77, 28, 25, 61],
       [37, 58, 56, 15, 34]])

In [43]:
np.linalg.det(detArray)

-7285549.999999978

In [45]:
detArray2=np.array([[1,2],[3,4]])

In [46]:
detArray2

array([[1, 2],
       [3, 4]])

In [47]:
np.linalg.det(detArray2)

-2.0000000000000004

In [48]:
arr=np.arange(0,10)

In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [53]:
arr[:3]=15

In [54]:
arr

array([15, 15, 15,  3,  4,  5,  6,  7,  8,  9])

In [55]:
arr=np.arange(10)

In [56]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr2=arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr2[:3]=100
arr2

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9])

In [61]:
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9])

In [63]:
arr=np.arange(10)

In [65]:
arr2=arr.copy()
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr2[:3]=100
arr2

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9])

In [67]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
newArray=np.arange(1,21)

In [73]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [74]:
newArray.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [75]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [76]:
newArray=newArray.reshape(5,4)

In [77]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [78]:
newArray[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [80]:
newArray[:3,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [81]:
newArray[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [91]:
newArray[:,:1]

array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17]])

In [92]:
newArray[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [93]:
arr = np.arange(1,11)

In [94]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
arr>3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [97]:
booleanArray=arr>3

In [98]:
arr[booleanArray]

array([ 4,  5,  6,  7,  8,  9, 10])

In [99]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [4]:
import numpy as np
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
numpy_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
print(numpy_array.max())

9


In [6]:
print(numpy_array.sum(axis = 1))

[ 1  5  9 13 17]
